package com.qhn.bhne.xhmusic.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qhn.bhne.xhmusic.mvp.entity.HistorySearch;

import com.qhn.bhne.xhmusic.db.HistorySearchDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historySearchDaoConfig;

    private final HistorySearchDao historySearchDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historySearchDaoConfig = daoConfigMap.get(HistorySearchDao.class).clone();
        historySearchDaoConfig.initIdentityScope(type);

        historySearchDao = new HistorySearchDao(historySearchDaoConfig, this);

        registerDao(HistorySearch.class, historySearchDao);
    }
    
    public void clear() {
        historySearchDaoConfig.clearIdentityScope();
    }

    public HistorySearchDao getHistorySearchDao() {
        return historySearchDao;
    }

}
